"""
some constants
"""

filter_options = [ 'All Pond Solutions 1000EF', 'All Pond Solutions 1400EF+', 'All Pond Solutions 2000EF', 'Atman (Amtop) AT-3388 1200L', 'Aqua El Fan Filter Plus Mikro', 'Aqua El Fan Filter Plus Mini', 'Aqua El Fan Filter Plus Fan-1', 'Aqua El Fan Filter Plus Fan-2', 'Aqua El Fan Filter Plus Fan-3', 'Aqua FX SPR-200', 'Aqua FX SPR-500', 'Aqua FX SPR-800', 'Aqua FX SPR-1100', 'Aqua FX SPR-1800', 'Aqua FX SPR-2200', 'Aqua One Aquis 500', 'Aqua One Aquis 550', 'Aqua One Aquis 700', 'Aqua One Aquis 750', 'Aqua One Aquis 1000', 'Aqua One Aquis 1050', 'Aqua One Aquis 1200', 'Aqua One Aquis 1250', 'Aqua One Aquis 2250', 'Aqua One Aquis 2450', 'Aqua One CF1000', 'Aqua Nova 600', 'Aqua Nova 1000', 'Aqua Nova 1200', 'Aqua Nova 1500', 'Aqua Nova 2000', 'Aqua World 150', 'Aqua World 500', 'Aquaclear Mini', 'Aquaclear 20', 'Aquaclear 30', 'Aquaclear 50', 'Aquaclear 70', 'Aquaclear 110', 'Aquaclear 150', 'Aquaclear 200', 'Aquaclear 300', 'Aquaclear 500', 'Aqueon ProFlex 1', 'Aqueon ProFlex 2', 'Aqueon ProFlex 3', 'Aqueon ProFlex 4', 'Aqueon QuietFlow 10', 'Aqueon QuietFlow 20', 'Aqueon QuietFlow 30', 'Aqueon QuietFlow 55', 'Aqua-Tech 5-15', 'Aqua-Tech 10-20', 'Aqua-Tech 20-40', 'Aqua-Tech 30-60', 'Aquarium Systems Millenium 1000', 'Aquarium Systems Millenium 2000', 'Aquarium Systems Millenium 3000', 'Azoo Oxygen 1 Plus', 'Azoo Oxygen 2 Plus', 'Azoo Oxygen 3 Plus', 'Azoo Oxygen 4 Plus', 'Azoo Oxygen 5 Plus', 'Azoo Oxygen 6 Plus', 'Azoo Oxygen 7 Plus', 'Azoo Oxygen 8 Plus', 'Azoo Oxygen 9 Plus', 'Azoo Oxygen 10 Plus', 'Azoo Oxygen 11 Plus', 'Boyu EF 10', 'Boyu EF 15', 'Boyu EF 20', 'Boyu EF 25', 'Boyu EF 35', 'Boyu EF 45', 'Cascade 80', 'Cascade 100', 'Cascade 150', 'Cascade 200', 'Cascade 300', 'Cascade 500', 'Cascade 600', 'Cascade 700', 'Cascade 1000', 'Cascade 1200', 'Cascade 1500', 'Clear Seal Magi 200', 'Clear Seal Magi 380', 'Clear Seal Magi 700', 'Clear Seal Magi 1000', 'Danner Aquamaster 350', 'Danner Skilter 250', 'Danner Skilter 400', 'Eden 316', 'Eden 320', 'Eden 325', 'Eden 328', 'Eden 501', 'Eheim 2026', 'Eheim 2028', 'Eheim 2032 Ecco Pro 130', 'Eheim 2034 Ecco Pro 200', 'Eheim 2036 Ecco Pro 300', 'Eheim 2071', 'Eheim 2073', 'Eheim 2075', 'Eheim 2076', 'Eheim 2078', 'Eheim 2080', 'Eheim 2126', 'Eheim 2128', 'Eheim 2211', 'Eheim 2213', 'Eheim 2215', 'Eheim 2217', 'Eheim 2222', 'Eheim 2224', 'Eheim 2226', 'Eheim 2227', 'Eheim 2229', 'Eheim 2250', 'Eheim 2260', 'Eheim 2262', 'Eheim Aquaball 2206', 'Eheim Aquaball 2208', 'Eheim Aquaball 2210', 'Eheim Aquaball 2212', 'Eheim Biopower 160', 'Eheim Biopower 200', 'Eheim Biopower 240', 'Eheim Ecco 2232', 'Eheim Ecco 2234', 'Eheim Ecco 2236', 'Eheim Liberty 100', 'Eheim Liberty 150', 'Eheim Liberty 200', 'Eheim Liberty 2040', 'Eheim Liberty 2041', 'Eheim Liberty 2042', 'Eheim Pickup 2006', 'Eheim Pickup 2008', 'Eheim Pickup 2010', 'Eheim Pickup 2012', 'Eheim Professional 3', 'Eheim Professional 3 2180', 'Hagen Aquaclear Mini', 'Hagen Aquaclear 20', 'Hagen Aquaclear 30', 'Hagen Aquaclear 50', 'Hagen Aquaclear 70', 'Hagen Aquaclear 110', 'Hagen Aquaclear 150', 'Hagen Aquaclear 200', 'Hagen Aquaclear 300', 'Hagen Aquaclear 500', 'Hagen Elite Hush 20', 'Hagen Elite Hush 35', 'Hagen Elite Hush 55', 'Hagen Elite Stingray 15', 'Hagen Elite Underwater Mini', 'Hagen Fluval Mini', 'Hagen Fluval 103', 'Hagen Fluval 104', 'Hagen Fluval 105', 'Hagen Fluval 106', 'Hagen Fluval 203', 'Hagen Fluval 204', 'Hagen Fluval 205', 'Hagen Fluval 206', 'Hagen Fluval 303', 'Hagen Fluval 304', 'Hagen Fluval 305', 'Hagen Fluval 306', 'Hagen Fluval 403', 'Hagen Fluval 404', 'Hagen Fluval 405', 'Hagen Fluval 406', 'Hagen Fluval C2', 'Hagen Fluval C3', 'Hagen Fluval C4', 'Hagen Fluval FX5', 'Hagen Fluval 1 Plus Internal', 'Hagen Fluval 2 Plus Internal', 'Hagen Fluval 3 Plus Internal', 'Hagen Fluval 4 Plus Internal', 'Hagen Fluval EDGE 6g', 'Hagen Fluval G3', 'Hagen Fluval G6', 'Hagen Fluval U1 Internal', 'Hagen Fluval U2 Internal', 'Hagen Fluval U3 Internal', 'Hagen Fluval U4 Internal', 'Hagen Marina Slim S10', 'Hagen Marina Slim S15', 'Hagen Marina Slim S20', 'Hagen Stingray 5', 'Hagen Stingray 10', 'Hagen Stingray 15', 'Hydor Crystal K10', 'Hydor Crystal K20', 'Hydor Crystal R05', 'Hydor Crystal R10', 'Hydor Crystal R20', 'Hydor Prime 10', 'Hydor Prime 30', 'Interpet EPF150', 'Interpet EPF250', 'Interpet EPF350', 'Interpet PF Mini', 'Interpet PF1', 'Interpet PF2', 'Interpet PF3', 'Interpet PF4', 'Jad SP-601E', 'Jad SP-602E', 'Jad SP-603E', 'Jad SP-604E', 'Jebo 178', 'Jebo 480 FC', 'Jebo 810', 'Jebo 819', 'Jebo 828', 'Jebo 829', 'Jebo 835', 'Jebo 839', 'JBJ Reaction 4-Stage', 'JBL CristalProfi e700', 'JBL CristalProfi e900', 'JBL CristalProfi e1500', 'JBL CristalProfi i40', 'JBL CristalProfi i60', 'JBL CristalProfi i80', 'JBL CristalProfi i100', 'JBL CristalProfi i200', 'Jungle Junior Dirt Magnet', 'Jungle Senior Dirt Magnet', 'Juwel Compact/Bioflow 3.0 + Pump 280', 'Juwel Compact/Bioflow 3.0 + Pump 400', 'Juwel Compact H/Bioflow 6.0 + Pump 400', 'Juwel Compact H/Bioflow 6.0 + Pump 600', 'Juwel Standard H/Bioflow 8.0 + Pump 1000', 'Juwel Jumbo/Bioflow Super + Pump 400', 'Juwel Jumbo/Bioflow Super + Pump 1000', 'Laguna Pressure-Flo 700', 'Lifeguard Aquatics FB 300', 'Lifeguard Aquatics FB 600', 'Lifeguard Aquatics FB 900', 'Lustar Hydro-Sponge Filter 0', 'Lustar Hydro-Sponge Filter 1', 'Lustar Hydro-Sponge Filter 2', 'Lustar Hydro-Sponge Filter 3', 'Lustar Hydro-Sponge Filter 4', 'Lustar Hydro-Sponge Filter 5', 'Marineland C-160', 'Marineland C-220', 'Marineland C-360', 'Marineland C-530', 'Marineland Duetto Mini', 'Marineland Duetto 50', 'Marineland Duetto 100', 'Marineland Eclipse 1', 'Marineland Eclipse 2', 'Marineland Eclipse 3', 'Marineland Eclipse System 3', 'Marineland Eclipse System 6', 'Marineland Eclipse System 12', 'Marineland Emperor 280', 'Marineland Emperor 400', 'Marineland HOT Magnum 250', 'Marineland HOT Magnum 250 Pro', 'Marineland Magnum 350', 'Marineland Magnum 350 Pro', 'Marineland Multi-Stage 160', 'Marineland Multi-Stage 220', 'Marineland Multi-Stage 360', 'Marineland Penguin 100B', 'Marineland Penguin 150B', 'Marineland Penguin 200B', 'Marineland Penguin 350B', 'Otto PF150G', 'Otto PF300G', 'Otto PF450G', 'Penn Plax Cascade 80', 'Penn Plax Cascade 100', 'Penn Plax Cascade 150', 'Penn Plax Cascade 200', 'Penn Plax Cascade 300', 'Penn Plax Cascade 700', 'Penn Plax Cascade 1000', 'Penn Plax Cascade 1200', 'Penn Plax Cascade 1500', 'Rapids Mini Canister', 'Red Sea Deco Art Nano', 'Rena Filstar iV1', 'Rena Filstar iV2', 'Rena Filstar iV3', 'Rena Filstar iV4', 'Rena Filstar XP1', 'Rena Filstar XP2', 'Rena Filstar XP3', 'Rena Filstar XP4', 'Sera Fil 60', 'Sera Fil 120', 'Skilter 250', 'Skilter 400', 'Sacem Marathon 300', 'Sacem Marathon 500', 'Sacem Marathon 1000', 'Sacem Marathon 1500', 'Sacem Marathon 2000', 'Sunsun HW302', 'Sunsun HW303-A', 'Sunsun HW303-B', 'Sunsun HW304-A', 'Sunsun HW304-B', 'Superfish Aqua-Flow 50', 'Superfish Aqua-Flow 100', 'Superfish Aqua-Flow 200', 'Superfish Aqua-Flow 400', 'Superfish Aqua-Flow XL', 'Superfish Aqua-Flow Aqua-Pro 200', 'Superfish Aqua-Flow Aqua-Pro 400', 'Superfish Aqua-Flow Aqua-Pro 600', 'Tetra Advanced Filtration 20-40', 'Tetra Advanced Filtration 30-60', 'Tetra EX400', 'Tetra EX600', 'Tetra EX700', 'Tetra EX1200', 'Tetra EX2400', 'Tetra Whisper 3i', 'Tetra Whisper 20', 'Tetra Whisper 30', 'Tetra Whisper 10-30i', 'Tetra Whisper 40', 'Tetra Whisper 60', 'Tetra Whisper EX20', 'Tetra Whisper EX30', 'Tetra Whisper EX45', 'Tetra Whisper EX70', 'Tetra Whisper 10I', 'Tetra Whisper 20I', 'Tetra Whisper 40I', 'Tetra Whisper PF10', 'Tetra Whisper PF150', 'Tetra Whisper PF300', 'Tetra Whisper PF500', 'TetraTec IN300+', 'TetraTec IN400+', 'TetraTec IN600+', 'TetraTec IN800+', 'TetraTec IN1000+', 'Tom Aquatics Rapids Mini Canister C-80', 'Tom Aquatics Rapids Power Filter PF80', 'Top Fin Power Filter 10', 'Top Fin Power Filter 20', 'Top Fin Power Filter 30', 'Top Fin Power Filter 40', 'Top Fin Power Filter 60', 'UNIMAX 150', 'UNIMAX 250', 'UNIMAX 500', 'UNIMAX 700', 'Zoo Med 318 Turtle Filter', 'Zoo Med 501 Turtle Filter', ]

filter_capacity=[ '105.6', '158.5', '264.2', '90.5', '13.2', '15.8', '26.4', '39.6', '66', '13.2', '33', '52.8', '72.6', '118.8', '145.3', '31.7', '34.8', '60.7', '65.1', '87.1', '91.5', '105.6', '110', '158.5', '171.7', '52.8', '39.6', '79.2', '105.6', '158.5', '211.3', '5.2', '21.1', '20', '20', '30', '50', '70', '110', '30', '50', '70', '110', '55', '110', '165', '220', '20', '30', '45', '60', '15', '20', '40', '60', '15', '60', '100', '30', '30', '15', '75', '25', '110', '50', '65', '25', '130', '10', '80', '90', '105', '120', '145', '170', '10', '20', '40', '60', '80', '30', '50', '65', '100', '150', '200', '17.1', '29', '59.4', '79.2', '70', '55', '100', '13.2', '26.4', '27.5', '44', '15.8', '92', '158', '34.3', '52.8', '79.2', '65', '95', '280', '105', '180', '320', '90', '160', '39', '65', '95', '160', '40', '65', '92.4', '90', '160', '265', '400', '396', '12', '16', '42', '60', '42.2', '52.8', '63.4', '35', '60', '80', '20', '35', '50', '20', '35', '50', '11.8', '15.8', '42.2', '52.8', '320', '320', '20', '20', '30', '50', '70', '110', '30', '50', '70', '110', '20', '35', '55', '15', '3', '11.8', '25', '25', '25', '25', '40', '40', '40', '45', '70', '70', '70', '70', '100', '100', '100', '100', '30', '50', '70', '400', '12', '24', '34', '57', '12.5', '80', '160', '15', '30', '40', '65', '10', '15', '20', '6', '12', '15', '13.2', '23.7', '39.6', '52.8', '52.8', '40', '120', '33', '55', '77', '10.5', '17.9', '23.7', '35.9', '48', '13.2', '25.6', '30.1', '61.9', '30', '83', '79.2', '113.2', '90.5', '113.2', '75.4', '200', '100', '29', '51.5', '105.6', '10.5', '21.1', '26.4', '42.2', '52.8', '10', '25', '12.9', '18.4', '31.7', '50.1', '121.5', '48.6', '121.5', '700', '300', '600', '900', '10', '10', '20', '40', '80', '125', '30', '55', '100', '150', '10', '10', '20', '30', '40', '50', '8', '16', '30', '55', '80', '55', '55', '100', '100', '30', '55', '100', '20', '30', '50', '70', '52.8', '105.6', '158.5', '10', '20', '40', '60', '80', '65', '100', '150', '200', '20', '3', '13.2', '19.8', '39.6', '52.8', '45', '75', '175', '265', '15.8', '31.7', '55', '125', '15.8', '26.4', '52.8', '105.6', '184.9', '66', '92.4', '92.4', '132.1', '132.1', '13.2', '26.4', '52.8', '105.6', '105.6', '52.8', '105.6', '158.5', '40', '60', '21.1', '31.7', '66', '132', '264', '3', '20', '30', '30', '40', '60', '20', '30', '45', '70', '10', '20', '40', '10', '30', '60', '100', '10.5', '15.8', '26.4', '39.6', '52.8', '20', '20', '10', '20', '30', '40', '60', '39.6', '66', '132.1', '184.9', '30', '30' ]

tank_names=[ '2.5g', '3g Eclipse System 3', '5g Eclipse Corner 5', '5g Eclipse Hex 5', '5.5g', '6g Eclipse System 6', '6g Fluval EDGE', '6.5g bookshelf', '8g Oceanic Biocube', '10g', '10g hex', '12g Current Aquapod 7050', '12g Eclipse System 12', '14g hex', '14g Oceanic Biocube', '15g', '15g high', '16g Aqueon bowfront', '20g hex', '20g high', '20g long', '20g x high', '23g flatback hex', '24g Current Aquapod 7051', '24g D-D Nano Cube 24', '25g', '26g bowfront', '26g flatback hex', '27g hex', '28g bowfront', '29g high', '29g Oceanic Biocube', '30g', '30g breeder', '30g hex', '30g Oceanic Cube', '30g x high', '33g flatback hex', '33g long', '34g Red Sea Max 130', '35g hex', '35g tall', '36g bowfront', '37g', '38g', '40g breeder', '40g flatback hex', '40g long', '44g pentagon', '45g', '46g bowfront', '50g', '52g flatback hex', '54g corner', '55g', '58g', '60g hex', '65g', '66g Red Sea Max 250', '70g corner', '72g bowfront', '75g', '90g', '90g bowfront', '90L Fluval Roma', '92g corner', '110g high', '120g high', '120g long', '125g', '125L Fluval Roma', '135g', '150g', '155g bowfront', '175g bowfront', '180g', '200L Fluval Roma', '210g', '220g', '240g', '240L Fluval Roma', '265g high', '280g long', '300g tall', '310g square', '340g', '375g', '500g' ]

tank_length=[ '12', '11', '10', '9', '16', '15', '16.5', '23.7', '12', '20', '14', '16.5', '20.5', '14', '14.5', '24', '20', '18.5', '18', '24', '30', '20', '24', '19.3', '17', '24', '24', '36', '18', '24', '30', '19', '36', '36', '17', '19.5', '24', '36', '48', '23', '23', '30', '30', '30', '36', '36', '36', '48', '22', '36', '36', '36', '48', '38', '48', '36', '27', '36', '36.5', '48', '48', '48', '48', '48', '60', '48', '48', '48', '60', '72', '80', '72', '72', '72', '72', '72', '100', '72', '72', '96', '120', '84', '72', '96', '48', '130', '96', '96']

tank_depth=[ '6', '7', '9', '9', '8', '8', '9.8', '7', '13.6', '10', '10', '12', '10', '12', '15.7', '12', '10', '12', '13', '12', '12', '10', '16', '16.4', '18.6', '12', '13', '11', '15', '15', '12', '20', '12', '18', '17', '20', '12', '13', '12', '18.7', '15', '12', '13', '12', '12', '18', '12', '12', '19', '12', '15', '18', '12', '15', '12', '18', '18', '18', '19', '14', '16', '18', '18', '15', '35', '19', '18', '24', '18', '18', '35', '18', '18', '21', '20', '24', '40', '24', '24', '24', '40', '24', '36', '24', '48', '24', '36', '48']

tank_height=[ '8', '11', '14', '15', '10', '14', '8.3', '9', '11.3', '12', '18', '13.75', '14', '20', '14', '12', '18', '16.5', '20', '16', '12', '24', '14', '17.5', '17.5', '20', '20', '16', '24', '18', '18', '17.6', '16', '12', '25', '17.5', '25', '16', '12', '18.2', '24', '22', '21', '22', '19', '16', '20', '16', '24', '23', '20', '18', '20', '22', '21', '21', '28', '24', '22', '25', '22', '20', '24', '29', '45', '24', '30', '24', '26', '22', '45', '24', '28', '24', '29', '24', '55', '29', '30', '24', '55', '30', '25', '30', '31', '25', '25', '25' ]

FILTER_DATA = dict(zip(filter_options, filter_capacity))

tank_ldh_dimensions = zip(tank_length, tank_depth, tank_height)

TANK_INFO = dict(zip(tank_names, tank_ldh_dimensions))

fish_species = [
    "Abei Puffer (Tetraodon abei)",
    "Achara Catfish (Leiarius marmoratus)",
    "Adolfo Cory (Corydoras adolfoi)",
    "Adonis Pleco (Acanthicus adonis)",
    "Aequidens Coeruleopunctatus (Aequidens coeruleopunctatus)",
    "selected>Aequidens Jenaro Herrera (Aequidens sp. Jennaro Herrera)",
    "Aequidens diadema (Aequidens diadema)",
    "Aequidens sp. Atabapo (Aequidens sp. Atabapo)",
    "African Arowana (Heterotis niloticus)",
    "African Butterfly Cichlid (Anomalochromis thomasi)",
    "African Butterfly Fish (Pantodon buchholzi)",
    "African Clawed Frog (Xenopus laevis)",
    "African Dwarf Frog (Hymenochirus boettgeri)",
    "African Filter Shrimp (Atya gabonensis)",
    "African Knifefish (Xenomystus nigri)",
    "African Leaf Fish (Ctenopoma acutirostre)",
    "African Pike (Hepsetus odoe)",
    "African Pipefish (Enneacampus ansorgii)",
    "Agassiz Cory (Corydoras agassizii)",
    "Ajamaru Rainbowfish (Melanotaenia ajamaruensis)",
    "Albino Bristlenose Pleco (Ancistrus cf. cirrhosus)",
    "Albino Cory (Corydoras aeneus)",
    "Albino Tiger Barb (Puntius tetrazona)",
    "Allens Rainbowfish (Chilatherina alleni)",
    "Alligator Gar (Atractosteus spatula)",
    "Alligator Pleco (Pterygoplichthys scrophus)",
    "Altolamprologus Calvus (Altolamprologus calvus)",
    "Altolamprologus Compressiceps (Altolamprologus compressiceps)",
    "Altum Angel (Pterophyllum altum)",
    "Amano Shrimp (Cardina multidentata)",
    "Amazon Leaf Fish (Monocirrhus polyacanthus)",
    "Amazon Puffer (Colomesus asellus)",
    "American Flagfish (Jordanella floridae)",
    "American Grass Shrimp (Palaemonetes kadiakensis)",
    "American Tigerfish (Datnioides quadrifasciatus)",
    "Andinoacara pulcher (Andinoacara pulcher)",
    "Andinoacara sp. Gold Saum (Andinoacara sp. Gold Saum)",
    "Andinoacara stalsbergi (Andinoacara stalsbergi)",
    "Angelfish (Pterophyllum scalare)",
    "Angelicus Botia (Botia kubotai)",
    "Angelicus Loach (Botia kubotai)",
    "Angelicus Pleco L073 (Hypancistrus sp. L073)",
    "Angfa Rainbowfish (Melanotaenia angfa)",
    "Antennae Stingray (Plesiotrygon iwamae)",
    "Apistogramma Black-Chin (Apistogramma sp. Black-Chin)",
    "Apistogramma Broad-banded (Apistogramma sp. Broad-banded)",
    "Apistogramma Mamor (Apistogramma sp. Mamor)",
    "Apistogramma Maulbr (Apistogramma sp. Maulbr)",
    "Apistogramma Orange-tail (Apistogramma cf. eunotus Orange-tail)",
    "Apistogramma Parrot (Apistogramma sp. Parrot)",
    "Apistogramma Resticulosa Mamor (Apistogramma cf. resticulosa Mamor)",
    "Apistogramma agassizii (Apistogramma agassizii)",
    "Apistogramma atahualpa (Apistogramma atahualpa)",
    "Apistogramma baenschi (Apistogramma baenschi)",
    "Apistogramma bitaeniata (Apistogramma bitaeniata)",
    "Apistogramma borellii (Apistogramma borellii)",
    "Apistogramma elizabethae (Apistogramma elizabethae)",
    "Apistogramma hongsloi (Apistogramma hongsloi)",
    "Apistogramma macmasteri (Apistogramma macmasteri)",
    "Apistogramma panduro (Apistogramma panduro)",
    "Apistogramma rupununi (Apistogramma rupununi)",
    "Apistogramma trifasciata (Apistogramma trifasciata)",
    "Apistogramma uaupesi (Apistogramma uaupesi)",
    "Apistogramma viejita (Apistogramma viejita)",
    "Apple Snail (Pomacea bridgesii)",
    "Arapaima gigas (Arapaima gigas)",
    "Arfak Rainbowfish (Melanotaenia arfakensis)",
    "Aristochromis christyi (Aristochromis christyi)",
    "Arrowhead Puffer (Tetraodon suvattii)",
    "Arulius Barb (Puntius tambraparniei)",
    "Asher Cory (Corydoras tukano C064)",
    "Asian Arowana (Scleropages formosus)",
    "Asian Upside Down Catfish (Mystus leucophasis)",
    "Assassin Snail (Antentome helena)",
    "Australian Pearl Arowana (Scleropages jardinii)",
    "Australian Smelt (Retropinna semoni)",
    "Axelrods Rainbowfish (Chilatherina axelrodi)",
    "Badis Badis (Badis badis)",
    "Bahia Red (Geophagus sp. Bahia Red)",
    "Bala Shark (Balantiocheilos melanopterus)",
    "Balloon Molly (Poecilia latipinna hybrid)",
    "Bamboo Shrimp (Atyopsis moluccensis)",
    "Banana Loach (Acantopsis choirorhynchos)",
    "Banded Archerfish (Toxotes jaculatrix)",
    "Banded Chromide (Etroplus suratensis)",
    "Banded Cichlid (Heros notatus)",
    "Banded Gourami (Colisa fasciata)",
    "Banded Leporinus (Leporinus fasciatus)",
    "Banded Rainbowfish (Melanotaenia trifasciata)",
    "Bandit Cory (Corydoras metae)",
    "Banjo Catfish (Bunocephalus coracoideus)",
    "Barred Rainbowfish (Chilatherina fasciata)",
    "Batanta Rainbowfish (Melanotaenia batanta)",
    "Bearded Cory (Scleromystax barbatus)",
    "Bee Shrimp (Caridina cantonensis sp. Bee)",
    "Bengal Loach (Botia dario)",
    "Bentos Tetra (Hyphessobrycon bentosi)",
    "Betta Imbellis (Betta imbellis)",
    "Betta Smaragdina (Betta smaragdina)",
    "Betta [Female] (Betta splendens)",
    "Betta [Male] (Betta splendens)",
    "Betta macrostoma (Betta macrostoma)",
    "Bigmouth Bass (Micropterus salmoides)",
    "Black Acara (Cichlasoma portalegrense)",
    "Black Bass (Micropterus salmoides)",
    "Black Belt Cichlid (Vieja maculicauda)",
    "Black Bullhead Catfish (Ameiurus melas)",
    "Black Cory (Corydoras schultzei)",
    "Black Diamond Cichlid (Paratilapia polleni)",
    "Black Fin Cory (Corydoras leucomelas)",
    "Black Ghost Knife Fish (Apteronotus albifrons)",
    "Black Kuhli (Pangio oblonga)",
    "Black Moor Goldfish (Carassius auratus)",
    "Black Neon Tetra (Hyphessobrycon herbertaxelrodi)",
    "Black Ocellatus (Lamprologus speciosus)",
    "Black Pacu (Colossoma macropomum)",
    "Black Phantom Tetra (Hyphessobrycon megalopterus)",
    "Black Ruby Barb (Puntius nigrofasciatus)",
    "Black Skirt Tetra (Gymnocorymbus ternetzi)",
    "Black Widow Tetra (Gymnocorymbus ternetzi)",
    "Black-Banded Rainbowfish (Melanotaenia nigrans)",
    "Blackline Rasbora (Rasbora borapetensis)",
    "Bleeding Heart Tetra (Hyphessobrycon erythrostigma)",
    "Blehers Rainbowfish (Chilatherina bleheri)",
    "Blind Cave Tetra (Astyanax jordani)",
    "Blood Parrot (Blood Parrot)",
    "Bloodfin Tetra (Aphyocharax anisitsi)",
    "Blue Acara (Aequidens pulcher)",
    "Blue Apple Snail (Pomacea bridgesii)",
    "Blue Back Blue Eye (Pseudomugil cyanodorsalis)",
    "Blue Botia (Yasuhikotakia modesta)",
    "Blue Dolphin (Cyrtocara moorii)",
    "Blue Emperor Tetra (Inpaichthys kerri)",
    "Blue Gourami (Trichogaster trichopterus)",
    "Blue Lyretail (Fundulopanchax gardneri gardneri)",
    "Blue Pearl Shrimp (Neocaridina cf. zhangjiajiensis var. blue)",
    "Blue Rainbowfish (Melanotaenia caerulea)",
    "Blue Ram (Mikrogeophagus ramirezi)",
    "Blue Sifter (Amphilophus robertsoni)",
    "Blue Tetra (Boehlkea fredcochui)",
    "Blue Tilapia (Oreochromis aureus)",
    "Bluefin Notho Killifish (Nothobranchius rachovii Beira 98)",
    "Bluegill Sunfish (Lepomis macrochirus)",
    "Boesemans Rainbowfish (Melanotaenia boesemani)",
    "Bolivian Ram (Mikrogeophagus altispinosus)",
    "Brilliant Rasbora (Rasbora einthovenii)",
    "Bristlenose Pleco (Ancistrus sp.)",
    "Bronze Cory (Corydoras aeneus)",
    "Brown Bullhead Catfish (Ameiurus nebulosus)",
    "Brown Camo Shrimp (Caridina sp. Brown Camo)",
    "Brown Hoplo (Hoplosternum thoracatum)",
    "Brown Pencilfish (Nannostomus beckfordi)",
    "Brown Puffer (Tetraodon turgidus)",
    "Buccochromis lepturus (Buccochromis lepturus)",
    "Buccochromis rhoadesii (Buccochromis rhoadesii)",
    "Bucktoothed Tetra (Exodon paradoxus)",
    "Buenos Aires Tetra (Hyphessobrycon anisitsi)",
    "Buettikoferi Bichir (Polypterus palmas buettikoferi)",
    "Buffalo Head Cichlid (Steatocranus sasuarius)",
    "Bulldog Pleco (Chaetostoma sp. aff. Milesi L187a)",
    "Bullseye Catfish (Horabagrus brachysoma)",
    "Bullseye Snakehead (Channa marulius)",
    "Bulolo Rainbowfish (Chilatherina bulolo)",
    "Bumble Bee Cichlid (Pseudotropheus Crabro)",
    "Bumblebee Catfish SA (Microglanis Iheringi)",
    "Bumblebee Cory (Corydoras tukano C064)",
    "Bumblebee Goby (Brachygobius xanthozona)",
    "Butterfly Goodeid (Ameca splendens)",
    "Butterfly Peacock (Aulonocara jacobfreibergi)",
    "Butterfly Pleco L168 (Dekeyseria brachyura L168)",
    "Butterfly Splitfin (Ameca splendens)",
    "Cairns Rainbowfish (Cairnsichthys rhombosomoides)",
    "Cameron Armoured Shrimp (Atyopsis gabonensis)",
    "Cardinal Shrimp (Caridina sp. Cardinal)",
    "Cardinal Tetra (Paracheirodon axelrodi)",
    "Celebes Halfbeak (Nomorhamphus liemi)",
    "Celebes Rainbowfish (Marosatherina ladigesi)",
    "Celestial Pearl Danio (Danio margaritatus)",
    "Ceylon Puffer (Tetraodon fluviatilis)",
    "Chameleon Fish (Badis badis)",
    "Champsochromis caeruleus (Champsochromis caeruleus)",
    "Chanchito (Australoheros oblongum)",
    "Channel Catfish (Ictalurus punctatus)",
    "Chao Phraya Giant Catfish (Pangasius sanitwongsei)",
    "Checker barb (Puntius oligolepis)",
    "Checkerboard Cichild (Dicrossus filamentosa)",
    "Checkerboard Cory (Scleromystax barbatus)",
    "Checkered Barb (Puntius oligolepis)",
    "Chequered Rainbowfish (Melanotaenia splendida inornata)",
    "Cherry Barb (Puntius titteya)",
    "Cherry Red Cichlid (Maylandia estherae)",
    "Cherry Shrimp (Neocaridina heteropoda)",
    "Cherry Spot Rasbora (Rasbora rubrodorsalis)",
    "Chilatherina pricei (Chilatherina pricei)",
    "Chili Rasbora (Boraras brigittae)",
    "Chinese Algae Eater (Gyrinocheilus aymonieri)",
    "Chinese Barb (Puntius semifasciolatus)",
    "Chocolate Cichlid (Hypselecara temporalis)",
    "Chocolate Gourami (Sphaerichthys osphromenoides)",
    "Chocolate Kuhli (Pangio oblonga)",
    "Chocolate Zebra Pleco L270 (Hypancistrus sp. L270)",
    "Christmas Fulu (Xystichromis phytophagus)",
    "Chuco Cichlid (Vieja godmanni)",
    "Cigar Shark (Leptobarbus hoevenii)",
    "Clarias Catfish (Clarias batrachus)",
    "Clown Killifish (Pseudepiplatys annulatus)",
    "Clown Knife (Notopterus chilata)",
    "Clown Loach (Chromobotia macracanthus)",
    "Clown Pleco (Panaque maccus)",
    "Cobalt Blue Zebra (Metriaclima callainos)",
    "Cockatoo Apisto (Apistogramma cacatuoides)",
    "Colombian Tetra (Hyphessobrycon columbianus)",
    "Comet Goldfish (Carassius auratus)",
    "Common Pleco (Pterygoplichthys pardalis)",
    "Common Stingray (Potamotrygon laticeps)",
    "Common Syno (Synodontis nigrita)",
    "Common Whiptail Catfish (Rineloricaria eigenmanni)",
    "Congo Bichir (Polypterus endlicheri congicus)",
    "Congo Puffer (Tetraodon miurus)",
    "Congo Tetra (Phenacogrammus interruptus)",
    "Convict (Cryptoheros nigrofasciatus)",
    "Copadichromis Azureus (Copadichromis azureus)",
    "Copadichromis Borleyi (Copadichromis borleyi)",
    "Copper Harlequin (Trigonostigma hengeli)",
    "Corona Rainbowfish (Melanotaenia corona)",
    "Corydoras C079 (Corydoras loxozonus)",
    "Corydoras C082 (Corydoras loxozonus)",
    "Corydoras C083 (Corydoras loxozonus)",
    "Corydoras duplicareus (Corydoras duplicareus)",
    "Corydoras incolicana (Corydoras incolicana)",
    "Crayfish (Cambaridae camburus)",
    "Crimsonspotted Rainbowfish (Melanotaenia duboulayi)",
    "Crown Pearlscale Goldfish (Carassius auratus)",
    "Crystal Red Shrimp (Caridina cantonensis sp. Crystal Red)",
    "Ctenochromis horei (Ctenochromis horei)",
    "Cuban Cichlid (Nandopsis tetracanthus)",
    "Cuban Gar (Atractosteus tristoechus)",
    "Cupid Cichlid (Biotodoma cupido)",
    "Cutteri Cichlid (Archocentrus sp. Cutteri)",
    "Cynotilapia Afra (Cynotilapia afra)",
    "Cynotilapia sp. White Top Hara (Cynotilapia sp. White Top Hara)",
    "Cyprichromis Leptosoma (Cyprichromis leptosoma)",
    "Cyprichromis Leptosoma Jumbo (Cyprichromis sp. Leptosoma Jumbo)",
    "Dainty Cory (Corydoras habrosus)",
    "Dalmatian Molly (Poecilia latipinna hybrid)",
    "Danio erythromicron (Danio erythromicron)",
    "Debauwi Catfish (Pareutropius buffei)",
    "Delhezi Bichir (Polypterus delhezi)",
    "Delicate Blue Eye (Pseudomugil tenellus)",
    "Denisoni Barb (Puntius denisonii)",
    "Diamond Tetra (Moenkhausia pittieri)",
    "Dimidiochromis compressicep (Dimidiochromis compressicep)",
    "Dimidiochromis strigatus (Dimidiochromis strigatus)",
    "Discus (Symphysodon aequifasciatus)",
    "Dojo Loach (Misgurnus anguillicaudatus)",
    "Domino Syno (Synodontis notata)",
    "Dourada (Brachyplatystoma rousseauxii)",
    "Dourada Zebra (Brachyplatystoma tigrinum)",
    "Dragon Goby (Gobioides brousonnetti)",
    "Dusky Millions Fish  (Phalloceros caudimaculatus)",
    "Dutch Ram (Mikrogeophagus ramirezi)",
    "Dwarf Chain Loach (Yasuhikotakia sidthimunki)",
    "Dwarf Cory (Corydoras hastatus)",
    "Dwarf Croaking Gourami (Trichopsis pumila)",
    "Dwarf Flag Cichlid (Laetacara curviceps)",
    "Dwarf Gourami (Colisa lalia)",
    "Dwarf Green Pike Cichlid (Crenicichla compressiceps)",
    "Dwarf Livebearer [Female] (Heterandria formosa)",
    "Dwarf Livebearer [Male] (Heterandria formosa)",
    "Dwarf Loach (Yasuhikotakia sidthimunki)",
    "Dwarf Molly (Poecilia chica)",
    "Dwarf Orange Crayfish (Cambarellus patzcuarensis sp. Orange)",
    "Dwarf Pencilfish (Nannostomus marginatus)",
    "Dwarf Petricola (Synodontis lucipinnis)",
    "Dwarf Puffer (Carinotetraodon travancoricus)",
    "Dwarf Rainbowfish (Melanotaenia maccullochi)",
    "Dwarf Rasbora (Boraras maculatus)",
    "Eastern Rainbowfish (Melanotaenia splendida)",
    "Eclipse Catfish (Horabagrus brachysoma)",
    "Electric Blue Hap (Sciaenochromis Fryeri)",
    "Electric Blue Jack Dempsey (Rocio octofasciatum)",
    "Electric Blue Johannii (Melanochromis johanni)",
    "Elephantnose Fish (Gnathonemus petersii)",
    "Ember Tetra (Hyphessobrycon amandae)",
    "Emerald Cichlid (Hypselecara temporalis)",
    "Emerald Eye Rasbora (Rasbora dorsiocellata macrophthalma)",
    "Emerald Green Cory (Brochis splendens)",
    "Emperor Snakehead (Channa marulioides)",
    "Emperor Tetra (Nematobrycon palmeri)",
    "Empire Gudgeon (Hypseleotris compressa)",
    "Endler (Poecilia wingei)",
    "Eretmodus Cyanostictus (Eretmodus cyanostictus)",
    "Espei Rasbora (Trigonostigma espei)",
    "European Catfish (Silurus glanis)",
    "European Wels Catfish (Silurus glanis)",
    "Exochochromis anagenys (Exochochromis anagenys)",
    "Exquisite Rainbowfish (Melanotaenia exquisita)",
    "Fahaka Puffer (Tetraodon lineatus)",
    "False Firemouth (Amphilophus robertsoni)",
    "False Glass Catfish (Kryptopterus macrocephalus)",
    "False Julii Cory (Corydoras trilineatus)",
    "False Rosy Tetra (Hyphessobrycon bentosi)",
    "False Siamese (Epalzeorhynchus sp.)",
    "False Upside Down Catfish (Synodontis nigrita)",
    "Fancy Goldfish (Carassius auratus)",
    "Fantail Goldfish (Carassius auratus)",
    "Farlowella Catfish (Farlowella acus)",
    "Featherfin Catfish (Synodontis euptera)",
    "Featherfin Cichlid (Cyathopharynx furcifer)",
    "Featherfin Rainbowfish (Iriatherina werneri)",
    "Festas Cichlid (Cichlasoma festae)",
    "Festivum (Mesonauta festivus)",
    "Figure Eight Puffer (Tetraodon biocellatus)",
    "Filament Barb (Puntius filamentosus)",
    "Filigree Cory (Scleromystax barbatus)",
    "Finescale Tigerfish (Datnioides microlepis)",
    "Finger Fish (Monodactylus argenteus)",
    "Fire Eel (Mastacembelus erythrotaenia)",
    "Fire Tetra (Hyphessobrycon flammeus)",
    "Firemouth (Thorichthys meeki)",
    "Five Banded Barb (Puntius pentazona)",
    "Flag Tetra (Hyphessobrycon Heterorhabdus)",
    "Flagtail Prochilodus (Semaprochilodus insignis)",
    "Flame Tetra (Hyphessobrycon flammeus)",
    "Flash Pleco (Panaque sp.)",
    "Florida Bass (Micropterus salmoides)",
    "Florida Flagfish (Jordanella floridae)",
    "Florida Gar (Lepisosteus platyrhincus)",
    "Flounder Pleco L168 (Dekeyseria brachyura L168)",
    "Flower Shrimp (Atyopsis moluccensis)",
    "Flower Stingray (Potamotrygon schroederi)",
    "Flowerhorn (Flowerhorn)",
    "Flowerhorn Short Body (Flowerhorn Short Body)",
    "Fly River Rainbowfish (Melanotaenia sexlineata)",
    "Flying Fox (Epalzeorhynchos kalopterus)",
    "Flyspeck Hardyhead (Craterocephalus stercusmuscarum)",
    "Forktail Rainbowfish (Pseudomugil furcatus)",
    "Fossorochromis rostratus (Fossorochromis rostratus)",
    "Freshwater Barracuda (Ctenolucius hujeta)",
    "Freshwater Flounder (Trinectes maculatus)",
    "Freshwater Shark (Wallago attu)",
    "Freshwater Sole (Brachirus selheimi)",
    "Frogmouth Catfish (Chaca chaca)",
    "Frontosa (Cyphotilapia frontosa)",
    "Furcata Rainbowfish (Pseudomugil furcata)",
    "Galaxy Rasbora (Danio margaritatus)",
    "Gangetic Leaf Fish (Nandus nandus)",
    "Gardneri Killifish (Fundulopanchax gardneri gardneri)",
    "Garnet Tetra (Hemigrammus pulcher)",
    "Geophagus Orange Head Tapajos (Geophagus sp Orange Head Tapajos)",
    "Geophagus Red Head Tapajos (Geophagus sp Red Head Tapajos)",
    "Geophagus altifrons (Geophagus altifrons)",
    "German Blue Ram (Mikrogeophagus ramirezi)",
    "Geto Loach (Botia dario)",
    "Ghost Shrimp (Palaemonetes sp.)",
    "Giant Danio (Perilampus aequipinnatus)",
    "Giant Gourami (Osphronemus goramy)",
    "Glass Bloodfin Tetra (Prionobrama filigera)",
    "Glass Catfish (Kryptopterus minor)",
    "Glo Fish (Danio rerio)",
    "Glowlight Danio (Danio choprai)",
    "Glowlight Tetra (Hemigrammus erythrozonus)",
    "Goby Pleco (Parotocinclus jumbo)",
    "Gold Barb (Puntius sachsii)",
    "Gold Laser Cory Cw010 (Corydoras sp. Cw010)",
    "Gold Nugget Pleco L018 (Baryancistrus sp. L018)",
    "Gold Nugget Pleco L081 (Baryancistrus sp. L081)",
    "Gold Nugget Pleco L085 (Baryancistrus sp. L085)",
    "Gold Nugget Pleco L177 (Baryancistrus sp. L177)",
    "Gold Tetra (Hemigrammus rodwayi)",
    "Golden Apple Snail (Golden ampullaria)",
    "Golden Barb (Puntius gelius)",
    "Golden Bristlenose Pleco (Ancistrus sp.)",
    "Golden Dwarf Barb (Barbus gelius)",
    "Golden Dwarf Cichlid (Nannacara anomala)",
    "Golden Gourami (Trichogaster trichopterus)",
    "Golden Killifish (Aplocheilus Lineatus)",
    "Golden Oto (Otocinclus affinis)",
    "Golden Pencilfish (Nannostomus beckfordi)",
    "Golden Ram (Mikrogeophagus ramirezi)",
    "Golden Red Tail Catfish (Horabagrus brachysoma)",
    "Golden Wonder Killifish (Aplocheilus Lineatus)",
    "Golden Zebra Danio (Danio rerio)",
    "Goldeneye Cichlid (Nannacara anomala)",
    "Goldfish (Carassius auratus)",
    "Goldie River Rainbowfish (Melanotaenia goldiei)",
    "Grants Peacock (Aulonocara stuartgranti)",
    "Green Barb (Puntius semifasciolatus)",
    "Green Chromide (Etroplus suratensis)",
    "Green Fire Tetra (Aphyocharax rathbuni)",
    "Green Neon Tetra (Paracheirodon simulans)",
    "Green Phantom Pleco (Hemiancistrus subviridis L200)",
    "Green Spotted Puffer (Tetraodon nigroviridis)",
    "Green Sunfish (Lepomis cyanellus)",
    "Green Terror (Andinoacara rivulatus)",
    "Green Tiger Barb (Puntius tetrazona)",
    "Greenstreaked Eartheater (Biotodoma cupido)",
    "Grime Rainbowfish (Glossolepis dorityi)",
    "Guinean Bichir (Polypterus ansorgii)",
    "Gulper Catfish (Asterophysus batrachus)",
    "Guppy (Poecilia reticulata)",
    "Gymnogeophagus meridionalis (Gymnogeophagus meridionalis)",
    "Half Banded Spiny Eel (Macrognathus circumcinctus)",
    "Half Barred Spiny Eel (Macrognathus circumcinctus)",
    "Hangel Rasbora (Trigonostigma hengeli)",
    "Haplochromis nyererei (Haplochromis nyererei)",
    "Haplochromis sp. 44 (Haplochromis sp. 44)",
    "Haplochromis sp. Ruby Green (Haplochromis sp. Ruby Green)",
    "Harlequin Rasbora (Trigonostigma heteromorpha)",
    "Harlequin Shark (Labeo variegatus)",
    "Harlequin Shrimp (Caridina cf. spongicola)",
    "Hatchet (Gasteropelecus sternicla)",
    "Head and Tail Light Tetra (Hemigrammus ocellifer)",
    "Hi Fin Peppered Cory (Scleromystax macropterus)",
    "Highfin Platy (Xiphophorus maculatus)",
    "Highlands Rainbowfish (Chilatherina campsi)",
    "Hillstream Loach (Gastromyzon ctenocephalus)",
    "Hogchoker (Trinectes maculatus)",
    "Honduran Red Point (Archocentrus sp. Honduran Red Point)",
    "Honey Blue Eye (Pseudomugil mellis)",
    "Honey Gourami (Trichogaster chuna)",
    "Hoplosternum (Hoplosternum littorale)",
    "Horned Nerite Snail (Clithon corona)",
    "Hornet Cichlid (Pseudotropheus Crabro)",
    "Horsefaced Loach (Acantopsis choirorhynchos)",
    "Hujeta Gar (Ctenolucius hujeta)",
    "Hunch Backed Limia (Limia nigrofasciata)",
    "Hypancistrus contradens (Hypancistrus contradens)",
    "Hypostomus plecostomus (Hypostomus plecostomus)",
    "Hystrix Stingray (Potamotrygon hystrix)",
    "Indian Glassfish (Parambassis ranga)",
    "Indonesian Snakehead (Channa micropeltis)",
    "Indonesian Tigerfish (Datnioides microlepis)",
    "Irian Jaya Rainbowfish (Melanotaenia irianjaya)",
    "Iridescent Shark (Pangasius hypophthalmus)",
    "Jack Dempsey (Rocio octofasciatum)",
    "Jaguar Cichlid (Parachromis managuensis)",
    "Japanese Algae Shrimp (Cardina multidentata)",
    "Japen Rainbowfish (Melanotaenia japenensis)",
    "Java Loach (Pangio oblonga)",
    "Jewel Cichlid (Hemichromis bimaculatus)",
    "Julidochromis Dickfeldi (Julidochromis dickfeldi)",
    "Julidochromis Marlieri (Julidochromis marlieri)",
    "Julidochromis Ornatus (Julidochromis ornatus)",
    "Julidochromis Regani (Julidochromis regani)",
    "Julidochromis Transcriptus (Julidochromis transcriptus)",
    "Julii Cory (Corydoras julii)",
    "Jurupari Eartheater (Satanoperca jurupari)",
    "Kamaka Rainbowfish (Melanotaenia kamaka)",
    "Kamaka Rainbowfish (Melanotaenia kamaka)",
    "Kenyi Cichlid (Pseudotropheus lombardoi)",
    "Keyhole Cichlid (Cleithracara maronii)",
    "King Tiger Pleco (Hypancistrus sp.)",
    "Kissing Gourami (Helostoma temminckii)",
    "Kiunga Blue Eye (Kiunga ballochi)",
    "Knight Goby (Stigmatogobius sadanunidio)",
    "Kribensis (Pelvicachromis pulcher)",
    "Kuhli Loach (Pangio kuhlii)",
    "Labeotropheus Fuelleborni (Labeotropheus fuelleborni)",
    "Labeotropheus trewavasae (Labeotropheus trewavasae)",
    "Labidochromis chisumulae (Labidochromis chisumulae)",
    "Lace Catfish (Synodontis nigrita)",
    "Lacerda Cory C015 (Scleromystax lacerdai C015)",
    "Lake Eacham Rainbowfish (Melanotaenia eachamensis)",
    "Lake Kutubu Rainbowfish (Melanotaenia lacustris)",
    "Lake Mbuta Rainbowfish (Pelangia mbutaensis)",
    "Lake Tebera Rainbowfish (Melanotaenia herbertaxelrodi)",
    "Lake Wanam Rainbowfish (Glossolepis wanamensis)",
    "Lampeye Killifish (Micropanchax macrophthalmus)",
    "Largemouth Bass (Micropterus salmoides)",
    "Least Killifish [Female] (Heterandria formosa)",
    "Least Killifish [Male] (Heterandria formosa)",
    "Leggetts Rainbowfish (Glossolepis leggetti)",
    "Lemon Tetra (Hyphessobrycon pulchripinnis)",
    "Leopard Bushfish (Ctenopoma acutirostre)",
    "Leopard Cory (Corydoras leopardus)",
    "Leopard Danio (Danio rerio)",
    "Leopard Frog Pleco (Peckoltia sp. L134)",
    "Leopard Gourami (Ctenopoma acutirostre)",
    "Leopard Pleco (Pterygoplichthys gibbiceps)",
    "Leopard Puffer (Tetraodon nigroviridis)",
    "Leopardfish (Phalloceros caudimaculatus)",
    "Leopoldi Stingray (Potamotrygon leopoldi)",
    "Lesser Spiny Eel (Macrognathus aculeatus)",
    "Lichnochromis acuticeps (Lichnochromis acuticeps)",
    "Licorice Gourami (Parosphromenus deissneri)",
    "Lima Shovelnose Catfish (Sorubim lima)",
    "Lionhead Cichlid (Steatocranus sasuarius)",
    "Long Nosed Loach (Acantopsis choirorhynchos)",
    "Long-Finned African Tetra (Alestes longipinnis)",
    "Long-Tailed River Stingray  (Plesiotrygon iwamae)",
    "Longear Sunfish (Lepomis megalotis)",
    "Longfin Zebra Danio (Danio rerio)",
    "Longnose Gar (Lepisosteus osseus)",
    "Lorentzs Rainbowfish (Chilatherina lorentzii)",
    "Loricaria cataphracta L062 (Loricaria cataphracta L062)",
    "Loricaria lata Eigenmann L010 (Loricaria lata eigenmann L010)",
    "Loricaria lentiginosa (Loricaria lentiginosa)",
    "Loricaria lundbergi (Loricaria lundbergi)",
    "Loricaria parnahybae (Loricaria parnahybae)",
    "Loricaria prolixa (Loricaria prolixa)",
    "Loricaria pumila (Loricaria pumila)",
    "Loricaria sp. Rio Atabapo (Loricaria sp. Rio Atabapo)",
    "Loricaria spinulifera (Loricaria spinulifera)",
    "Lyretail Killifish (Aphyosemion australe)",
    "Macaw Cichlid (Hypsophrys nicaraguensis)",
    "Macaw Cichlid [Female] (Hypsophrys nicaraguensis)",
    "Macaw Cichlid [Male] (Hypsophrys nicaraguensis)",
    "Macmaster Dwarf Cichlid (Apistogramma macmasteri)",
    "Madagascar Rainbowfish (Bedotia geayi)",
    "Maingano Mbuna (Melanochromis cyaneorhabdos)",
    "Maison Peacock (Aulonocara maisoni)",
    "Malaya Shrimp (Caridina sp. Malaya)",
    "Malaysian Trumpet Snail (Melanoides tuberculata)",
    "Mamberamo Rainbowfish (Glossolepis multisquamata)",
    "Mango Pleco (Baryancistrus sp. L047)",
    "Marakeli Cichlid (Paratilapia polleni)",
    "Marble Goby (Oxyeleotris marmorata)",
    "Marble Hatchet (Carnegiella strigata)",
    "Marble Loach (Botia kubotai)",
    "Marble Molly (Poecilia sphenops)",
    "Marbled Bichir (Polypterus palmas polli)",
    "Marbled Hatchet (Carnegiella strigata)",
    "Marbled Pim (Leiarius marmoratus)",
    "Marbled Whiptail (Loricaria simillima)",
    "Mayan Cichlid (Cichlasoma urophthalmus)",
    "Maylands Rainbowfish (Melanotaenia maylandi)",
    "Mbu Puffer (Tetraodon mbu)",
    "McCullochi Rainbowfish (Melanotaenia maccullochi)",
    "Mega Clown Pleco L340 (Hypancistrus sp. L340)",
    "Melanochromis Auratus (Melanochromis auratus)",
    "Melanochromis Chipokae (Melanochromis chipokae)",
    "Melanochromis cyaneorhabdos (Melanochromis cyaneorhabdos)",
    "Melon Barb (Puntius fasciatus)",
    "Metriaclima estherae (Maylandia estherae)",
    "Metriaclima sp Aurora Yellow (Metriaclima sp Aurora Yellow)",
    "Metriaclima sp. Msobo (Metriaclima sp. Msobo)",
    "Microrasbora kubotai (Microrasbora kubotai)",
    "Midas Cichlid (Amphilophus citrinellus)",
    "Midnight Catfish (Auchenipterichthys coracoideus)",
    "Milomo Hap (Placidochromis milomo)",
    "Misool Rainbowfish (Melanotaenia misoolensis)",
    "Molly (Poecilia sphenops)",
    "Mono Argentus (Monodactylus argenteus)",
    "Mono Sebae (Monodactylus sebae)",
    "Monster Wolf Fish (Hoplias aimara)",
    "Moonlight Gourami (Trichogaster microlepis)",
    "Mosquito Rasbora (Boraras brigittae)",
    "Motoro Stingray (Potamotrygon motoro)",
    "Mottled Loach (Acanthocobitis botia)",
    "Mountain Rainbowfish (Melanotaenia monticola)",
    "Mrs Schwartz Cory (Corydoras robineae)",
    "Mubi Rainbowfish (Melanotaenia mubiensis)",
    "Murray River Rainbowfish (Melanotaenia fluviatilis)",
    "Murray River Rainbowfish (Melanotaenia fluviatilis)",
    "Mystery Snail (Pomacea cuprina)",
    "Nana Rasbora (Microdevario nana)",
    "Needlenose Gar (Xenentodon cancila)",
    "Neocaridina Heteropoda Shrimp (Neocaridina heteropoda wild)",
    "Neolamprologus Brevis (Neolamprologus brevis)",
    "Neolamprologus Brichardi (Neolamprologus brichardi)",
    "Neolamprologus Fasciatus (Neolamprologus fasciatus)",
    "Neolamprologus Leleupi (Neolamprologus leleupi)",
    "Neolamprologus Multifasciatus (Neolamprologus multifasciatus)",
    "Neolamprologus Pulcher (Neolamprologus Pulcher)",
    "Neolamprologus Similis (Neolamprologus similis)",
    "Neolamprologus Tretocephalus (Neolamprologus tretocephalus)",
    "Neon Blue Cichlid (Paracyprichromis nigripinnis)",
    "Neon Dwarf Rainbowfish (Melanotaenia praecox)",
    "Neon Tetra (Paracheirodon innesi)",
    "Nerite Snail (Nerita sp.)",
    "New Guinea Rainbowfish (Melanotaenia affinis)",
    "New Guinea Rainbowfish (Melanotaenia affinis)",
    "New Guinea Tigerfish (Datnioides campbelli)",
    "Nicaraguan Cichlid (Hypsophrys nicaraguensis)",
    "Nicaraguan Cichlid [Female] (Hypsophrys nicaraguensis)",
    "Nicaraguan Cichlid [Male] (Hypsophrys nicaraguensis)",
    "Nile Puffer (Tetraodon lineatus)",
    "Nile Tilapia (Oreochromis niloticus)",
    "Nimbochromis Venustus (Nimbochromis venustus)",
    "Nimbochromis livingstonii (Nimbochromis livingstonii)",
    "Ninja Shrimp (Caridina serratirostris)",
    "Northern Mountain Swordtail (Xiphophorus nezahualcoyotl)",
    "Ocellatus Gold (Lamprologus ocellatus)",
    "Odessa Barb (Puntius ticto)",
    "Ogilbys Rainbowfish (Melanotaenia ogilbyi)",
    "Olga Cory (Corydoras simulatus)",
    "Olive Nerite Snail (Neritina natalensis sp. Zebra)",
    "One-Spot Betta (Betta unimaculata)",
    "Opaline Gourami (Trichogaster trichopterus)",
    "Oranda Goldfish (Carassius auratus)",
    "Orange Chromide (Etroplus maculatus)",
    "Orange Delight Shrimp (Caridina sp. Orange Delight)",
    "Orange Peacock (Aulonocara stuartgranti maleri)",
    "Orangespotted Snakehead (Channa aurantimaculata)",
    "Orangespotted Sunfish (Lepomis humilis)",
    "Ornate Bichir (Polypterus ornatipinnis)",
    "Ornate Rainbowfish (Rhadinocentrus ornatus)",
    "Ornate Tetra (Hyphessobrycon bentosi)",
    "Oscar (Astronotus ocellatus)",
    "Oto (Otocinclus vittatus)",
    "Otocinclus vestitus (Otocinclus vestitus)",
    "Otopharynx lithobates (Otopharynx lithobates)",
    "P. Joselimaianus L001 L022 (Pterygoplichthys joselimaianus L001 L022)",
    "Pacific Blue Eye (Pseudomugil signifer)",
    "Pacific Sturgeon (Acipenser transmontanus)",
    "Pakistani Loach (Botia almorhae)",
    "Palmas Bichir (Polypterus palmas palmas)",
    "Panda Cory (Corydoras panda)",
    "Panda Dwarf Cichlid (Apistogramma nijsseni)",
    "Panda Garra (Garra flavatra)",
    "Panda Tetra (Aphyocharax paraguayensis)",
    "Pangasius larnaudii (Pangasius larnaudii)",
    "Pangasius micronemus (Pangasius micronemus)",
    "Pangasius nasutus (Pangasius nasutus)",
    "Paradise Fish (Macropodus opercularis)",
    "Parkinson Rainbowfish (Melanotaenia parkinsoni)",
    "Paroon Shark (Pangasius sanitwongsei)",
    "Parrot Cichlid (Hoplarchus psittacus)",
    "Pastel Cichlid (Amphilophus alfari)",
    "Payara (Hydrolycus scomberoides)",
    "Peacock Bass Monoculus (Cichla monoculus)",
    "Peacock Bass Ocellaris (Cichla ocellaris)",
    "Peacock Bass Orinocensis (Cichla orinocensis)",
    "Peacock Bass Temensis (Cichla temensis)",
    "Peacock Eel (Macrognathus siamensis)",
    "Peacock Gudgeons (Tateurndina Ocellicauda)",
    "Pearl Danio (Danio albolineatus)",
    "Pearl Gourami (Trichogaster leerii)",
    "Pearly Ocellatus (Lamprologus Stappersi)",
    "Peckoltia sp. L387 (Peckoltia sp. L387)",
    "Penguin Tetra (Thayeria boehlkei)",
    "Peppered Cory (Corydoras paleatus)",
    "Peppermint Pleco (Parancistrus nudiventris)",
    "Phuket Loach (Schistura robertsi )",
    "Pictus Catfish (Pimelodus pictus)",
    "Pike Cichlid (Crenicichla sp. Xingu)",
    "Pink Tailed Chalceus (Chalceus macrolepidotus)",
    "Piraiba (Brachyplatystoma filamentosum)",
    "Pitbull Pleco (Parotocinclus jumbo)",
    "Placidochromis electra (Placidochromis electra)",
    "Platinum Acara (Aequidens latifrons)",
    "Platinum Hatchet (Thoracocharax stellatus)",
    "Platy (Xiphophorus maculatus)",
    "Polka Dot Loach (Botia kubotai)",
    "Polypterus Bichir Lapradei (Polypterus lapradei)",
    "Polypterus mokelembembe (Polypterus mokelembembe)",
    "Polypterus teugelsi (Polypterus teugelsi)",
    "Pond Snail (Pond Snail)",
    "Popondetta Blue-eye (Pseudomugil connieae)",
    "Port Acara (Cichlasoma portalegrense)",
    "Prehistoric Monster Fish (Thalassophryne amazonica)",
    "Pristella Tetra (Pristella maxillaris)",
    "Pseudotropheus Acei (Pseudotropheus acei)",
    "Pseudotropheus Demasoni (Pseudotropheus demasoni)",
    "Pseudotropheus Elongatus (Pseudotropheus elongatus)",
    "Pseudotropheus Estherae (Maylandia estherae)",
    "Pseudotropheus Saulosi (Pseudotropheus Saulosi)",
    "Pseudotropheus Socolofi (Pseudotropheus socolofi)",
    "Pseudotropheus flavus (Pseudotropheus flavus)",
    "Pseudotropheus sp Kingsizei (Metriaclima pulpican)",
    "Pumpkinseed (Lepomis gibbosus)",
    "Pumpkinseed Sunfish (Lepomis gibbosus)",
    "Pungas Catfish (Pangasius pangasius)",
    "Purple Spotted Gudgeon (Morgurnda adspersa)",
    "Purple Zebra Shrimp (Potamalpheops sp.)",
    "Purring Gourami (Trichopsis pumila)",
    "Pygmy Cory (Corydoras pygmaeus)",
    "Pygmy Gourami (Trichopsis pumila)",
    "Pygmy Rainbowfish (Melanotaenia pygmaea)",
    "Queen Loach (Botia dario)",
    "Rainbow Cichlid (Archocentrus multispinosus)",
    "Rainbow Shark (Epalzeorhynchos frenatum)",
    "Rainbow Snakehead (Channa bleheri)",
    "Ramshorn Snail (Planorbidae)",
    "Ramu Rainbowfish (Glossolepis ramuensis)",
    "Raphael Catfish (Platydoras costatus)",
    "Red Bellied Pacu (Piaractus brachypomus)",
    "Red Bellied Piranha (Pygocentrus nattereri)",
    "Red Breasted Acara (Laetacara dorsigera)",
    "Red Cherry Shrimp (Neocaridina heteropoda)",
    "Red Devil Cichlid (Amphilophus labiatus)",
    "Red Dwarf Rasbora (Microrasbora rubescens)",
    "Red Empress (Protomelas Taeniolatus)",
    "Red Eye Tetra (Moenkhausia sanctaefilomenae)",
    "Red Fin Caudopunk (Neolamprologus caudopunctatus)",
    "Red Goldflake Shrimp (Caridina sp. Red Goldflake)",
    "Red Hump Eartheater (Geophagus steindachneri)",
    "Red Lined Torpedo Barb (Puntius denisonii)",
    "Red Peacock (Aulonocara hansbaenschi)",
    "Red Phantom Tetra (Hyphessobrycon sweglesi)",
    "Red Rainbowfish (Glossolepis incisus)",
    "Red Shoulder Peacock (Aulonocara hansbaenschi)",
    "Red Striped Eartheater (Geophagus surinamensis)",
    "Red Tail Barracuda (Acestrorhynchus falcatus)",
    "Red Tailed Black Shark (Epalzeorhynchos bicolor)",
    "Red Tailed Catfish (Phractocephalus hemioliopterus)",
    "Red Tailed Redeye Puffer (Carinotetraodon irrubesco)",
    "Red Tailed Silverside (Bedotia geayi)",
    "Red Terror (Cichlasoma festae)",
    "Red Top Cobalt Cichlid (Metriaclima greshakei)",
    "Red Tupfel Shrimp (Caridina serrata sp. Red Tupfel)",
    "Red Zebra (Maylandia estherae)",
    "Red-Finned Rainbowfish (Melanotaenia rubripinnis)",
    "Redbreast Sunfish (Lepomis auritus)",
    "Redear Sunfish (Lepomis microlophus)",
    "Redeye Tilapia (Oreochromis hornorum)",
    "Redfin Tilapia (Oreochromis mossambicus)",
    "Redhead Cichlid (Vieja synspila)",
    "Redhead Severum (Heros sp. Rotkeil)",
    "Redline Barb (Puntius denisonii)",
    "Redline Rasbora (Rasbora pauciperforata)",
    "Redline Shark (Puntius denisonii)",
    "Redstripe Rasbora (Rasbora pauciperforata)",
    "Redtail Rasbora (Rasbora borapetensis)",
    "Redtail Splitfin (Xenotoca eiseni)",
    "Reedfish (Erpetoichthys calabaricus)",
    "Reticulated Stingray (Potamotrygon scobina)",
    "Rhino Pleco (Pterygoplichthys scrophus)",
    "Rhomb Barb (Puntius rhomboocellatus)",
    "Riffle Shrimp (Australatya striolata)",
    "Rio Negro Dwarf Cichlid (Nannacara adoketa)",
    "Robertsons Cichlid (Amphilophus robertsoni)",
    "Ropefish (Erpetoichthys calabaricus)",
    "Rose Danio (Danio roseus)",
    "Rosy Barb (Puntius conchonius)",
    "Rosy Finned Tetra (Hyphessobrycon rosaceus)",
    "Rosy Red Minnow (Pimephales promelas)",
    "Rosy Tetra (Hyphessobrycon rosaceus)",
    "Royal Farlowella Catfish (Sturisoma panamense)",
    "Royal Pleco (Panaque nigrolineatus)",
    "Rubberlip Pleco (Chaetostoma sp. aff. Milesi L187a)",
    "Rubbernose Pleco (Chaetostoma sp. aff. Milesi L187a)",
    "Ruby Barb (Puntius nigrofasciatus)",
    "Ruby Shark (Epalzeorhynchos frenatum)",
    "Rummynose Rasbora (Sawbwa resplendens)",
    "Rummynose Tetra (Hemigrammus bleheri)",
    "Rusty Cichild (Iodotropheus Sprengerae)",
    "Ryukin Goldfish (Carassius auratus)",
    "Sabretooth Tetra (Hydrolycus scomberoides)",
    "Saddled Bichir (Polypterus endlicheri endlicheri)",
    "Sailfin Molly (Poecilia latipinna)",
    "Sailfin Pleco (Pterygoplichthys gibbiceps)",
    "Sajica Cichlid (Archocentrus sajica)",
    "Salmon-Red Rainbowfish (Glossolepis incisus)",
    "Salvini Cichlid (Cichlasoma Salvini)",
    "San Juan Cory (Corydoras bilineatus)",
    "Sand Loach (Acanthocobitis botia)",
    "Sawbwa Barb (Sawbwa resplendens)",
    "Scarlet Badis (Dario Dario)",
    "Scat (Scatophagus argus)",
    "Schwartz Cory (Corydoras schwartzi)",
    "Scissortail Rasbora (Rasbora trilineata)",
    "Scleromystax prionotos (Scleromystax prionotos)",
    "Senegal Bichir (Polypterus senegalus senegalus)",
    "Sentani Rainbowfish (Chilatherina sentaniensis)",
    "Sepik Rainbowfish (Glossolepis kabia)",
    "Serpae Tetra (Hyphessobrycon eques)",
    "Severum (Heros efascticious)",
    "Shark Catfish (Hexanematichthys seemanni)",
    "Shortnose Gar (Lepisosteus platostomus)",
    "Shovelnose Sturgeon (Scaphirhynchus platorynchus)",
    "Siamese Algae Eater (Crossocheilus siamensis)",
    "Siamese Tiger (Datnioides pulcher)",
    "Siamese Tigerfish (Datnioides polota)",
    "Silver Arowana (Osteoglossum bicirrhosum)",
    "Silver Dollar (Metynnis argenteus)",
    "Silver Flying Fox (Crossocheilus reticulatus)",
    "Silver Hatchet (Gasteropelecus sternicla)",
    "Silver Prochilodus (Semaprochilodus taeniurus)",
    "Silver Rainbowfish (Chilatherina crassispinosa)",
    "Silvertip Tetra (Hasemania nana)",
    "Sixbar Distichodus (Distichodus sexfasciatus)",
    "Skunk Botia (Yasuhikotakia morleti)",
    "Skunk Cory (Corydoras arcuatus)",
    "Skunk Loach (Yasuhikotakia morleti)",
    "Slant Nose Gar (Ctenolucius hujeta)",
    "Slender Rainbowfish (Melanotaenia gracilis)",
    "Smallmouth Bass (Micropterus dolomieu)",
    "Snakehead Fighter (Betta channoides)",
    "Snowball Shrimp (Neocaridina cf. zhangjiajiensis var. white)",
    "Solar Catfish (Horabagrus brachysoma)",
    "Sorong Rainbowfish (Melanotaenia fredericki)",
    "South American Leaf Fish (Monocirrhus polyacanthus)",
    "South American Puffer (Colomesus asellus)",
    "Southern Checkmark Cichlid (Vieja godmanni)",
    "Sparkling Gourami (Trichopsis pumila)",
    "Spiny Eel (Macrognathus aculeatus)",
    "Spot Loach (Acanthocobitis botia)",
    "Spotfin Goby Cichlid (Tanganicodus irsacae)",
    "Spotted Blue Eye (Pseudomugil gertrudae)",
    "Spotted Climbing Perch (Ctenopoma acutirostre)",
    "Spotted Gar (Lepisosteus oculatus)",
    "Spotted Headstander (Chilodus punctatus)",
    "Spotted Hillstream Loach (Gastromyzon punctulatus)",
    "Spotted Port Hoplo (Hoplosternum thoracatum)",
    "Spotted Rainbowfish  (Glossolepis maculosus)",
    "Spotted Raphael Catish (Agamyxis pectinifrons)",
    "Spotted Rubberlip Pleco L187a (Chaetostoma milesi L187a)",
    "Starlight Bristlenose Pleco L183 (Ancistrus dolichopterus L183)",
    "Steindachner Dwarf Cichlid (Apistogramma steindachneri)",
    "Sterbai Cory (Corydoras sterbai)",
    "Stonelapping Minnow (Garra cambodgiensis)",
    "Striped Glass Catfish (Kryptopterus macrocephalus)",
    "Striped Panchax Killifish (Aplocheilus Lineatus)",
    "Stripefin Eartheater (Gymnogeophagus rhabdotus)",
    "Stripped Loach (Acanthocobitis botia)",
    "Stripped Raphael Catish (Platydoras armatulus)",
    "Sturgeon Catfish (Platystomatichthys sturio)",
    "Sumo Loach (Schistura balteata)",
    "Sun Catfish (Horabagrus brachysoma)",
    "Sunburst Platy (Xiphophorus maculatus)",
    "Sunset Coral Dwarf Platy (Xiphophorus maculatus)",
    "Sunset Platy (Xiphophorus variatus)",
    "Swift Rasbora (Trigonostigma hengeli)",
    "Swordtail (Xiphophorus hellerii)",
    "Swordtail [Female] (Xiphophorus hellerii)",
    "Swordtail [Male] (Xiphophorus hellerii)",
    "Synodontis Multipunctatus (Synodontis multipunctatus)",
    "Synodontis Petricola (Synodontis petricola)",
    "Synodontis eupterus (Synodontis euptera)",
    "Synodontis notatus (Synodontis notata)",
    "Tail Spot Pygmy Cory (Corydoras hastatus)",
    "Tailbar Cichlid (Vieja hartwegi)",
    "Taiwan Reef (Protomelas sp. Steveni)",
    "Talking Catfish (Platydoras costatus)",
    "Tami River Rainbowfish (Glossolepis pseudoincisus)",
    "Tandanus Catfish (Tandanus Tandanus)",
    "Teacup Stingray (Potamotrygon scobina)",
    "Telmatochromis brichardi (Telmatochromis brichardi)",
    "Telmatochromis dhonti (Telmatochromis dhonti)",
    "Tequila Splitfin (Zoogoneticus tequila)",
    "Texas Cichlid (Herichthys cyanoguttatus)",
    "The Pearl Eartheater (Geophagus brasiliensis)",
    "Thinbar Datnoid (Datnioides undecimradiatus)",
    "Threadfin Acara (Acarichthys heckelii)",
    "Threadfin RainbowFish (Iriatherina werneri)",
    "Three Lined Cory (Corydoras trilineatus)",
    "Three Lined Rasbora (Rasbora trilineata)",
    "Three Spot Gourami (Trichogaster trichopterus)",
    "Tiger Barb (Puntius tetrazona)",
    "Tiger Danio (Devario maetaengensis)",
    "Tiger Loach (Syncrossus hymenophysa)",
    "Tiger Muskie (Esox masquinongy x lucius)",
    "Tiger Oscar (Astronotus ocellatus)",
    "Tiger Pleco L002 (Peckoltia vittata L002)",
    "Tiger Shovelnose Catfish (Platystoma tigrinum)",
    "Tiger Shrimp (Caridina cantonensis sp. Tiger)",
    "Tigrinus Catfish (Brachyplatystoma tigrinum)",
    "Tinfoil Barb (Barbodes schwanenfeldii)",
    "Tire Track Eel (Mastacembelus armatus)",
    "Tramitichromis Intermedius (Tramitichromis sp. Intermedius)",
    "Trapdoor Snail (Cipangopaludina chinensis)",
    "Tricolor Cichlid (Cichlasoma Salvini)",
    "Trimac (Amphilophus trimaculatus)",
    "Tropheus Duboisi (Tropheus duboisi)",
    "Tropheus Moorii (Tropheus moorii)",
    "Tropical Gar (Atractosteus tropicus)",
    "Tucano Cory (Corydoras tukano C064)",
    "Turquoise Cichlid (Amphilophus robertsoni)",
    "Turquoise Rainbowfish (Melanotaenia lacustris)",
    "Twig Catfish (Farlowella vittata)",
    "Twinbar Platy (Xiphophorus maculatus)",
    "Two Line Cory (Corydoras parallelus)",
    "Two Spot Gourami (Trichogaster trichopterus)",
    "Uaru Cichlid (Uaru amphiacanthoides)",
    "Upside Down Catfish (Synodontis nigriventris)",
    "Uruguayan Eartheater (Gymnogeophagus australis)",
    "Vampire Shrimp (Atya gabonensis)",
    "Venezuelan Pygmy Cory (Corydoras habrosus)",
    "Vieja fenestrata (Vieja fenestrata)",
    "Von Rio Tetra (Hyphessobrycon flammeus)",
    "Waigeo Rainbowfish (Melanotaenia catherinae)",
    "Walking Catfish (Clarias batrachus)",
    "Wallago leeri (Wallago leeri)",
    "Warmouth (Lepomis gulosus)",
    "Weather Loach (Misgurnus anguillicaudatus)",
    "Weeksi Bichir (Polypterus weeksii)",
    "West African Bichir (Polypterus retropinnis)",
    "Western Rainbowfish (Melanotaenia australis)",
    "Whisker Shrimp (Macrobrachium sp.)",
    "White Cheeked Goby (Rhinogobius wui)",
    "White Cichlid (Vieja argentea)",
    "White Cloud Mountain Minnow (Tanichthys albonubes)",
    "White Skirt Tetra (Gymnocorymbus ternetzi)",
    "White Sturgeon (Acipenser transmontanus)",
    "Whiteseam Fighter (Betta albimarginata)",
    "Whiteseam Fighter (Betta albimarginata)",
    "Widebar Datnoid (Datnioides pulcher)",
    "Wolf Cichlid (Parachromis dovii)",
    "Wolf Fish (Hoplias malabaricus)",
    "Wood Shrimp (Atyopsis moluccensis)",
    "X-Ray Tetra (Pristella maxillaris)",
    "Xenotilapia bathyphilus (Xenotilapia bathyphilus)",
    "Xenotilapia ochrogenys (Xenotilapia ochrogenys)",
    "Xenotilapia papilio (Xenotilapia papilio)",
    "Yellow Acara (Aequidens metae)",
    "Yellow Belly Cichlid (Cichlasoma Salvini)",
    "Yellow Bullhead Catfish (Ameiurus natalis)",
    "Yellow Convict (Cryptoheros nanoluteus)",
    "Yellow Lab (Labidochromis caeruleus)",
    "Yellow Peacock (Aulonocara baensch)",
    "Yellow Perch (Perca flavescens)",
    "Yellow Shrimp (Neocaridina heterpoda var. yellow)",
    "Yoyo Loach (Botia almorhae)",
    "Zamora Woodcat (Auchenipterichthys coracoideus)",
    "Zebra Apple Snail (Asolene spixi)",
    "Zebra Danio (Danio rerio)",
    "Zebra Loach (Botia striata)",
    "Zebra Nerite Snail (Neritina natalensis sp. Zebra)",
    "Zebra Obliquidens (Astatotilapia latifasciata)",
    "Zebra Oto (Otocinclus cocama)",
    "Zebra Pleco (Hypancistrus zebra)",
    "Zebra Spiny Eel (Mastacembelus zebrinus)",
    "Zebra Tilapia (Tilapia buttikoferi)",
    "Zig Zag Spiny Eel (Macrognathus circumcinctus)",
    "Zipper Loach (Acanthocobitis botia)",
]
